# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apertura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Apertura', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Modelo', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ISO', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Lente', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Velocidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Velocidad', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
