# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Archivo', models.FileField(upload_to='documents/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('Descripcion', models.CharField(blank=True, max_length=255)),
                ('fk_ISO', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.ISO')),
                ('fk_album', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='albums.Album')),
                ('fk_apertura', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.Apertura')),
                ('fk_camara', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.Camara')),
                ('fk_lente', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.Lente')),
                ('fk_velocidad', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='equipo.Velocidad')),
            ],
        ),
    ]
