# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='Titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
